back/update_vendors.sh

Updating HTTP to HTTPS for Vendor Database, this will fix the download issue.

Updating HTTP to HTTPS for Vendor Database

---

.env
Dockerfile
README.md
docker-compose.yml
dockerfiles/README.md
dockerfiles/start.sh
dockerfiles/user-mapping.sh

Cleaned up Readme & added permission mapping
@Macleykun helped with cleaning up of the Docekrfile and start.sh script

Permission mapping

---

Dockerfile

I have added nmap to the docker file because the nmap function in the UI requires it
Fixes #5 
Thanks for this great image!

Update Dockerfile to include nmap

---

front/css/dark-patch.css
front/index.php

- add fixes to dark-patch.css
- apple darkmode to login page

Add Darkmode to login page

---

README.md

Fix nickname

---

back/pialert.py
config/pialert.conf

Added configuration and adapted NTFY function to allow use of selfhosted instance of NTFY

Added use selfhosted ntfy

---

back/pialert.py
config/pialert.conf

So now also working with authentication

authentication NTFY

---

Dockerfile

An init manager is useful to help reap zombie processes. Since PiAlert spawns a lot of subprocesses for its various tools like arp-scan and nmap there is a decent possiblity of some of these showing up in a long lived container.
Can read more about the benefits of init managers here:
https://github.com/krallin/tini#why-tini
Adds maybe 50KB to the image. Added it as entrypoint to not break any custom docker commands users might be using instead of the default command.
Validated that processes all spawn nicely locally:
```bash
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2376   504 ?        Ss   18:30   0:00 tini -- /home/pi/pialert/dockerfiles/start.sh
root         7  0.0  0.0   2480   516 ?        S    18:30   0:00 /bin/sh …
```

Add tini as init manager to handle potential zombie processes

---

front/php/templates/footer.php

This should work as per https://github.com/jokob-sk/Pi.Alert/issues/209

feat: Place buildnumber and version in footer.

---

front/php/templates/language/es_es.php

Big thanks to @antoniog for giving me the file with all new english strings added!
I didn't test this, but I hope this won't broke anything.

Update spanish strings

---

pialert/database.py
pialert/publishers/webhook.py

Split it up

---

.github/workflows/docker_cache-cleaner.yml
.github/workflows/docker_dev.yml
.github/workflows/docker_prod.yml
docker-compose.yml

Manages a build cache and keeps it clear from untagged layers

Speedup docker builds with a cache

---

.github/workflows/docker_dev.yml
.github/workflows/docker_prod.yml

fix: github packages 403

---

pialert/__main__.py

Fixes #283 
Fixes the update check spam by properly updating the `last_version_check` variable after a check is made.
Also removes duplicate time variables that serve the same purpose and have the same value throughout the loop.

Fix update check interval

---

back/report_template.html
back/report_template_new_version.html
pialert/reporting.py

<h3>Update report_template.html</h3>
- Modified creator banner url repot_template.html --> report_template.html
- Modified the creators banner adding to cvc90
- Removed several white spaces between banner and <html> tag
- Changed the background color in the table (bgcolor=#00c0ef --> bgcolor=#4b99d3)
- Changed the color of the text to white in the table (bgcolor=#ffffff --> bgcolor=#4b99d3)
- Changed the background color in td (bgcolor=#F5F5F5 --> bgcolor=#F1F5F5)
- Changed the background color in the footer table (bgcolor=#46802e --> bgcolor=#3c8dbc)
- Added in the footer table the color of the text to white (color: white)
- Changed footer text
<h3>Update report_template_new_version.html</h3>
- Modified creator banner url repot_template.html --> …

Modified the style of the reports

---

back/report_template.html
back/report_template_new_version.html
pialert/reporting.py

Reverts jokob-sk/Pi.Alert#315
```bash
pialert    |   File "/home/pi/pialert/pialert/reporting.py", line 1
pialert    |     <!-- ---------------------------------------------------------------------------
pialert    |     ^
pialert    | SyntaxError: invalid syntax
pialert    | mkdir: cannot create directory '/run/php': File exists
pialert    | Starting nginx: nginx.
pialert    | Traceback (most recent call last):
pialert    |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
pialert    |     return _run_code(code, main_globals, None,
pialert    |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
pialert    |     exec(code, run_globals)
pialert    |   File "/home/pi/pialert/pialert/__main__.py", line 29, in <module>
pialert    |     from networkscan import …
```

Revert "Modified the style of the reports"

---

front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json

<h3>Update en_us.json</h3>
- Changed the content of the "System info" menu variable ("Navigation_SystemInfo" : "System Information" --> "Navigation_SystemInfo" : "System info")
<h3>Update es_es.json</h3>
- Changed the content of the "System info" menu variable ("Navigation_SystemInfo" : "Información del sistema" --> "Navigation_SystemInfo" : "Info del sistema")
<h3>Update de_de.json</h3>
- Changed the content of the "System info" menu variable ("Navigation_SystemInfo" : "Systeminformationen" --> "Navigation_SystemInfo" : "System info")

Pi.alert fix menu variable navigation system info

---

front/php/templates/build.php
front/php/templates/version.php
pialert/reporting.py

<h3>Update reporting.py</h3>
- Added new code "VERSION" to report version in report file
- Added new code "BUILD" to report version in report file
- Updated "REPORT_DATE" comment tag
- Updated "SERVER_NAME" comment tag
<h3>Create version.php</h3>
- Created file version.php
- Added new php code to search for version file and if it doesn't find it, it shows the file not found error
-  Added the creators banner
- Updated blank spaces
<h3>Create build.php</h3>
- Created build.php file
- Added new php code to search for build file and if it doesn't find it, it shows the file not found error
- Added the creators banner
- Updated blank spaces

Add new function reporting

---

back/report_template.html
back/report_template_new_version.html

<h3>Update report_template.html</h3>
- Fix banner creators
<h3>Create report_template_new_version.html</h3>
- Fix banner creators

Fix banners creators in report

---

front/systeminfo.php

<h3>Update systeminfo.php</h3>
- Updated the "Memory Statistics" formula variables
- Updated "Memory Statistics" echo variables
- Added new formula variables for "CPU Temp"
- Modified section "General"
- Added new section "System"
- Added new section "CPU"
- Added new section "Memory"
- Change of order of "General" section
- Change of order of "This Client" section
- Modified "Memory" section
- Updated "Storage usage" section

Corrections and improvements in the "System info" menu

---

front/php/templates/footer.php

<h3>Update footer.php</h3>
- Updated the creators banner
- updated comments
- Updated footer code
- Clean up blanks
- Code reduction

Update footer to show version and build

---

back/report_template_new_version.html
front/maintenance.php
front/php/templates/footer.php
front/systeminfo.php

<h3>Update footer.php</h3>
- Fix banner creators
<h3>Update systeminfo.php</h3>
- Fix banner creators
<h3>Update maintenance.php</h3>
- Fix banner creators
<h3>Update report_template_new_version.html</h3>
- Fix banner creators

Multiple creators banner fixes

---

.github/workflows/docker_dev.yml

<h3>Update docker_dev.yml</h3>
- Added "get_version" variable
- Added variable "Create .VERSION file"

Fix version docker_dev

---

front/plugins/website_monitor/config.json

<h3>Update config.json of "Website_monitor" plugin</h3>
- Updated config.json file for the "Spanish" language

Update config.json of "Website_monitor" plugin

---

.github/workflows/docker_dev.yml

<h3>Update docker_dev.yml</h3>
- Updated "get_version" variable (Changed to "dev")

Fixed bug to get version in docker dev

---

front/systeminfo.php

<h3>Update systeminfo.php</h3>
- Added new section of variables "Network stats"
- Updated "Storage usage" section
- Updated "Network" section

Corrections and improvements in the "System info" menu v3

---

.github/workflows/docker_dev.yml

<h3>Update docker_dev.yml</h3>
- Updated "get_version" variable (Changed to "dev")

Fixed bug to get version in docker dev (V3)

---

front/php/templates/header.php
front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json

<h3>Update header.php</h3>
- Updated "Report" menu icon
<h3>Update es_es.json</h3>
- Updated translation variable "Report"
<h3>Update en_us.json</h3>
- Updated translation variable "Report"
<h3>Update de_de.json</h3>
- Updated translation variable "Report"

Corrections and improvements in the "Report" menu

---

front/css/pialert.css

<h3>Update header.php</h3>
- Added option for "Back Button" to hide it on small screens
- Added option for "Next Button" to hide it on small screens
- Added option for "Reload Button" to hide it on small screens
- Added option for "Full Screen Button" to hide it on small screens

Fixed overflow header on mobile

---

front/php/templates/header.php

<h3>Update header.php</h3>
- Fixed tag "span" in "Navigation_Presence"

Fixed tag <span> in "Navigation_Presence"  

---

front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json
front/plugins/arp_scan/config.json
front/plugins/set_password/config.json
front/plugins/undiscoverables/config.json
front/pluginsCore.php
front/systeminfo.php

<h3>Update pluginsCore.php</h3>
- Added new translation variable "Plugins_Out_of"
<h3>Update es_es.json</h3>
- Added new translation variable "Plugins_Out_of"
- Added new translation variable "Systeminfo_General"
- Added new translation variable "Systeminfo_This_Client"
- Added new translation variable "Systeminfo_System"
- Added new translation variable "Systeminfo_Motherboard"
- Added new translation variable "Systeminfo_CPU"
- Added new translation variable "Systeminfo_Memory"
- Added new translation variable "Systeminfo_Storage"
- Added new translation variable "Systeminfo_Storage_usage"
- Added new translation variable "Systeminfo_Network"
- Added new translation variable "Systeminfo_Network_Hardware"
- Added new translation variable …

Multiple fixes in translations

---

front/devices.php
front/help_faq.php
front/maintenance.php
front/php/templates/language/es_es.json
front/presence.php
front/report.php
front/settings.php
front/systeminfo.php

<h3>Update systeminfo.php</h3>
- Fixed missing icon in page title
<h3>Update settings.php</h3>
- Fixed missing icon in page title
<h3>Update report.php</h3>
- Fixed missing icon in page title
<h3>Update presence.php</h3>
- Fixed missing icon in page title
<h3>Update maintenance.php</h3>
- Fixed missing icon in page title
- Fixed missing icon in page subtitle
<h3>Update help_faq.php</h3>
- Fixed missing icon in page title
<h3>Update devices.php</h3>
- Fixed missing icon in page title
<h3>Update maintenance.php</h3>
- Fixed missing icon in page title
<h3>Update es_es.json</h3>
- Removed icon of translation variable "HelpFAQ_Title"

Multiple fixes to missing icon in page title

---

pialert/plugin.py

Sorry I made a typo in that last commit of my last PR.
Thanks for your work though, I've been setting it up for the last little while.

Fix typo in last SQL PR

---

front/php/templates/header.php

<h3>Update header.php</h3>
- Fixed <span> tag in menu options

Fixed <span> tag in menu options in header.php

---

front/plugins/nmap_services/config.json

<h3>Update config.json (Plugin Nmap)</h3>
- Added new variables for the Spanish translation

Update config.json (Plugin Nmap)

---

front/plugins/dhcp_servers/config.json

<h3>Update config.json (front/plugins/dhcp_servers)</h3>

Rogue DHCP plugin translation

---

front/plugins/pihole_scan/config.json

<h3>Update config.json (front/plugins/pihole_scan)</h3>

Pihole plugin translation

---

front/plugins/nmap_services/config.json

<h3>Update config.json (front/plugins/nmap_services)</h3>

Translation of the plugin Nmap Services

---

front/plugins/dhcp_leases/config.json

<h3>Update config.json (front/plugins/dhcp_leases)</h3>

Translation of the plugin DHCP Leases

---

front/plugins/snmp_discovery/config.json

<h3>Update config.json (front/plugins/snmp_discovery)</h3>

Translation of the plugin SNMP Discovery

---

front/plugins/unifi_import/config.json

<h3>Update config.json (front/plugins/unifi_import)</h3>

Translation of the plugin UniFi Import

---

front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json
front/presence.php

<h3>Update presence.php (front)</h3>
<h3>Update en_us.json (/front/php/templates/language)</h3>
- Added new translation variable "Presence_Loading"
<h3>Update es_es.json (/front/php/templates/language)</h3>
- Added new translation variable "Presence_Loading"
<h3>Update de_de.json (/front/php/templates/language)</h3>
- Added new translation variable "Presence_Loading"

Translation in text "spinner" in presence.php

---

front/php/templates/language/es_es.json

<h3>Update es_es.json (front/php/templates/language/)</h3>
- Added translation variable "DevDetail_button_DeleteEvents"

Fixed translation of the "Delete Events" button

---

front/plugins/README.md
front/plugins/README_ES.md

<h2>Create</h2>
<h3>Create readme es.md (front/plugins/)</h3>
- The "README_ES.md" file has been created ("README.md" file translated into Spanish)
<h2>Update</h2>
<h3>Update readme.md (front/plugins/)</h3>
- Added link to see Spanish version

Pi.alert new file readme es.md (plugins)

---

front/plugins/website_monitor/README_ES.md

<h3>Created README_ES.md (front/plugins/website_monitor)</h3>
- Created the README_ES.md file (front/plugins/website_monitor) which is a version of README.md (front/plugins/website_monitor) translated into Spanish.

Created README_ES.md (front/plugins/website_monitor)

---

front/plugins/undiscoverables/README_ES.md

<h3>Created README_ES.md (front/plugins/undiscoverables)</h3>
- Created the README_ES.md file (front/plugins/undiscoverables) which is a version of README.md (front/plugins/undiscoverables) translated into Spanish.

Created README_ES.md (front/plugins/undiscoverables)

---

front/plugins/pihole_scan/README_ES.md

<h3>Created README_ES.md (front/plugins/pihole_scan)</h3>
- Created the README_ES.md file (front/plugins/pihole_scan) which is a version of README.md (front/plugins/pihole_scan) translated into Spanish.

Created README_ES.md (front/plugins/pihole_scan)

---

front/plugins/set_password/README_ES.md

<h3>Created README_ES.md (front/plugins/set_password)</h3>
- Created the README_ES.md file (front/plugins/set_password) which is a version of README.md (front/plugins/set_password) translated into Spanish.

Created README_ES.md (front/plugins/set_password)

---

front/plugins/dhcp_leases/README_ES.md

<h3>Created README_ES.md (front/plugins/dhcp_leases)</h3>
- Created the README_ES.md file (front/plugins/dhcp_leases) which is a version of README.md (front/plugins/dhcp_leases) translated into Spanish.

Created README_ES.md (front/plugins/dhcp_leases)

---

front/plugins/dhcp_servers/README_ES.md

<h3>Created README_ES.md (front/plugins/dhcp_servers)</h3>
- Created the README_ES.md file (front/plugins/dhcp_servers) which is a version of README.md (front/plugins/dhcp_servers) translated into Spanish.

Created README_ES.md (front/plugins/dhcp_servers)

---

front/plugins/known_template__ignore/README_ES.md

<h3>Created README_ES.md (front/plugins/known_template)</h3>
- Created the README_ES.md file (front/plugins/known_template) which is a version of README.md (front/plugins/known_template) translated into Spanish.

Created README_ES.md (front/plugins/known_template)

---

front/plugins/newdev_template/README_ES.md

<h3>Created README_ES.md (front/plugins/newdev_template)</h3>
- Created the README_ES.md file (front/plugins/newdev_template) which is a version of README.md (front/plugins/newdev_template) translated into Spanish.

Created README_ES.md (front/plugins/newdev_template)

---

front/plugins/pholus_scan/README_ES.md

<h3>Created README_ES.md (front/plugins/pholus_scan)</h3>
- Created the README_ES.md file (front/plugins/pholus_scan) which is a version of README.md (front/plugins/pholus_scan) translated into Spanish.

Created README_ES.md (front/plugins/pholus_scan)

---

front/plugins/unifi_import/README_ES.md

<h3>Created README_ES.md (front/plugins/unifi_import)</h3>
- Created the README_ES.md file (front/plugins/unifi_import) which is a version of README.md (front/plugins/unifi_import) translated into Spanish.

Created README_ES.md (front/plugins/unifi_import)

---

front/deviceDetails.php
front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json

<h3>Update deviceDetails.php (front/)</h3>
- Added "DevDetail_Loading" translation variable in various sections
<h3>Update en_us.json (front/php/templates/language)</h3>
- Added translation variable "DevDetail_Loading"
<h3>Update es_es.json (front/php/templates/language)</h3>
- Added translation variable "DevDetail_Loading"
<h3>Update de_de.json (front/php/templates/language)</h3>
- Added translation variable "DevDetail_Loading"

Translation "Loading/Spinner" in deviceDetails.php

---

front/plugins/nmap_services/README_ES.md

<h3>Created README_ES.md (front/plugins/nmap_services)</h3>
- Created the README_ES.md file (front/plugins/nmap_services) which is a version of README.md (front/plugins/nmap_services) translated into Spanish.

Created README_ES.md (front/plugins/nmap_services)

---

front/plugins/snmp_discovery/README_ES.md

<h3>Created README_ES.md (front/plugins/snmp_discovery)</h3>
- Created the README_ES.md file (front/plugins/snmp_discovery) which is a version of README.md (front/plugins/snmp_discovery) translated into Spanish.

Created README_ES.md (front/plugins/snmp_discovery)

---

front/plugins/arp_scan/README_ES.md

<h3>Created README_ES.md (front/plugins/arp_scan)</h3>
- Created the README_ES.md file (front/plugins/arp_scan ) which is a version of README.md (front/plugins/arp_scan ) translated into Spanish.

Created README_ES.md (front/plugins/arp_scan)

---

front/plugins/README_ES.md

<h3>Update README_ES.md (front/plugins/)</h3>
- Updating the file to be up to date with the English version

Updating the file README_ES.md to be up to date with the English version

---

front/plugins/pholus_scan/config.json

<h3>Update config.json (front/plugins/pholus_scan/)</h3>
- Updated config.json file with new Spanish translation variables.

Pi.alert new pholus scan plugin translations v2

---

dockerfiles/README_ES.md

<h3>Create README_ES.md (dockerfiles)</h3>
- Created the README_ES.md file (dockerfiles) which is a version of README.md (dockerfiles) translated into Spanish.

New translation in dockerfiles section

---

pialert/README_ES.md

<h3>Create README_ES.md (pialert)</h3>
- Created the README_ES.md file (pialert) which is a version of README.md (pialert) translated into Spanish.

New translation in PiAlert section

---

front/php/templates/language/de_de.json
front/php/templates/language/en_us.json
front/php/templates/language/es_es.json
front/systeminfo.php

- New function has been added to count running processes.
- Some features have been improved to be more accurate.
- Code order has been optimized to increase performance.
- Fixed an issue in "Network Hardware".
- Code Cleanup
<h3>Update systeminfo.php (front)</h3>
- Added new function "system_process_count" to see the number of processes executed in the system
- Added new comments in functions
- Added new comments in "System stats"
- Added new comments in "General stats"
- Changed the order of functions
- Fix  "Network Hardware"
- Code cleanup in the "Storage" section
- Cleaning and fixing code in the "Storage usage" section
<h3>Update en_us.json (/front/php/templates/language/)</h3>
- Added translation variable …

Pi.Alert fixes improvements System Info v6

---

front/plugins/csv_backup/config.json

- Fix tag code
<h3>Update config.json (/front/plugins/csv_backup/)</h3>
- Fix tag code

Pi.Alert - Fixes CSV Backup (Plugin) translations v2

---

front/js/pialert_common.js

- Loading problem with reverse proxies of the initDeviceListAll_JSON() function, fixes loading url in the initDeviceListAll_JSON() function
<h3>Update pialert_common.js (/front/js/)</h3>
- Fix url in initDeviceListAll_JSON() function

Pi.Alert - Fix pialert_common.js

---

front/plugins/README.md
front/plugins/README_DE.md
front/plugins/README_ES.md

The plugin readme has been updated to be updated to the latest version and available in several languages.
<h3>Create README_DE.md (/front/plugins/)</h3>
- Created file "README_DE.md", which is a copy of the file "README.md" but translated into German.
<h3>Update README.md (/front/plugins/)</h3>
- Added flag in subtitle translations
- Added American flag in subtitle translations
- Added German flag in subtitle translations
- Fixed style in subtitle translations
- Removed "Community translations of this file" in footer
<h3>Update README_ES.md (/front/plugins/)</h3>
- Added flag in subtitle translations
- Added American flag in subtitle translations
- Added German flag in subtitle translations
- Fixed style in subtitle translations …

Pi.Alert - Fix readme files for plugins

---

front/css/pialert.css
front/network.php

This PR fixes some alignment issues in the network diagram and fixes some broken markup there as well. This is related to #465
Example screenshot

Network cleanup

---

front/plugins/_publisher_pushover/README.md
front/plugins/_publisher_pushover/config.json
front/plugins/_publisher_pushover/pushover.py

I've seen the question for Pushover support a couple of time in the Repo,
and Ive also noticed the possibility of using Apprise.
However i did not want to Host another Service locally, just for these kinda notifications.
And thanks to the plugin system the effort was minimal.
I tested the Plugin with the latest Code and the Docker image.

Add Pushover Support

---

Dockerfile.alpine
dockerfiles/pre-setup.sh
dockerfiles/setup.sh
install/pialert.conf.template

PR for https://github.com/jokob-sk/Pi.Alert/issues/577
x86 image is 229MB, arm64 a bit bigger, 240MB :)

Adding support for alpine based image

---

.dockerignore
Dockerfile
dockerfiles/pre-setup.sh

Hi @jokob-sk
Some further tweaks to alpine based image, adding several files into .dockerignore file.
usbutils package is not needed as alpine comes with busybox built-in lsusb command.

Removing unneeded package, small tweaks

---

Dockerfile

Adding lsblk package

---

front/plugins/_publisher_pushover/config.json
front/plugins/_publisher_pushover/pushover.py

When specifying a device name, notifications only get sent to the device.

Add Pushover device support

---

dockerfiles/setup.sh

Improving chmod in setup.sh to apply proper permissions on files and directories.

Improve chmod in setup.sh

---

front/css/pialert.css
front/settings.php

I updated the title text color in the settings cards from blue to white for better visibility against the green background. Additionally, I replaced toggle icons with solid and regular circles to reduce their perceived interactivity.

Design improvements

---

Dockerfile

Adding nmap-scripts package to fix https://github.com/jokob-sk/NetAlertX/issues/623

Update Dockerfile with nmap-scripts

---

Dockerfile
dockerfiles/pre-setup.sh
dockerfiles/setup.sh
install/netalertx.template.conf

Upgrading base image to 3.20 and php to 8.3.
This should fix https://github.com/jokob-sk/NetAlertX/pull/688

upgrading base image to Alpine 3.20, upgrading php to 8.3

---

front/plugins/_publisher_mqtt/config.json
front/plugins/_publisher_mqtt/mqtt.py

I'm currently running my broker with TLS (mqtts) and I'm unable to publish any topic. This PR adds TLS support.

Add MQTT TLS support

---

front/plugins/mikrotik_scan/mikrotik.py

Change the MTSCAN plugin with the correct name

fix: mtscan plugin

---

front/plugins/_publisher_telegram/README.md
front/plugins/_publisher_telegram/config.json
front/plugins/_publisher_telegram/tg.py

Hello! I added a notification plugin for direct work with telegram, without apprise

Add Telegram publisher

---

front/userNotifications.php

Hi @jokob-sk,
Changed the "absolute URL" target to "relative URL" in userNotifications.php for viewing reports, this is a fix for issues with reverse proxy servers.
<h3>Update userNotifications.php (/front/userNotifications.php)</h3>
Changed the destination "absolute URL" to "relative URL" in reports to fix issues for reverse proxies
<h2>Test</h2>
Tested locally and works fine

Changed the "absolute URL" target to "relative URL" in userNotifications.php for viewing reports

---

front/plugins/mikrotik_scan/README.md

@jokob-sk updated README as requested in #940

better readme for the MikroTik plugin

---

front/plugins/asuswrt_import/config.json
front/plugins/asuswrt_import/script.py

Fixes https://github.com/jokob-sk/NetAlertX/discussions/963#discussioncomment-11880870
There is also no issue with special characters in the password, tested.

[ASUSWRT] Added router port to configurtation

---

Dockerfile
dockerfiles/init.sh

Adding option to set user ID and GID running the application.
Related to https://github.com/jokob-sk/NetAlertX/issues/974 and https://github.com/jokob-sk/NetAlertX/issues/939

Adding option to set user ID and GID

---

dockerfiles/README.md
dockerfiles/init.sh
docs/FILE_PERMISSIONS.md

Updating default user ID and user GID to 102/82 to match latest image ID/GID.

Update default PUID and PGID, and update documentation

---

front/userNotifications.php

Hi @jokob-sk,
Changed the absolute path URL to relative path URL in userNotifications.php, this is a fix for issues with reverse proxy servers.
<h3>Update userNotifications.php (/front/userNotifications.php)</h3>
Changed three absolute path URLs to relative path URLs
<h2>Test</h2>
Tested locally and works fine

Changing absolute path URL to relative path URL in userNotifications.php

---

front/plugins/newdev_template/config.json

`longet` should have been `longer`

Fix minor typo "longet"

---

Dockerfile

Time to update base image to the latest version of Alpine Linux. :)
I've built it locally, no issues, and I was able to start the container.

Updating base image to Alpine 3.22

---

server/scan/device_handling.py

Reverts jokob-sk/NetAlertX#1089
Uhhh, I thought this pull was ready but it throws further errors down the pipeline. Will fix and update and resubmit with all fixes once known to be stable.

Revert "Sanitize device fields and prevent crash with numeric hostnames"

---

.devcontainer/scripts/setup.sh

There is an error where the logs folder was not properly linked.  This fixes that error.

Fix log directory setup in setup.sh
