- back/pialert.py
- front/css/dark-patch.css
The history graph was calling the incorrect SQL table and was causing negative numbers as seen in the screenshot below. This is now fixed.
In addition to this, I have made the information cards at the top more compact - mainly for mobile users. Let me know what you think, and remove that change if you don't like it. 
I have also fixed a bug in the dark mode css that causes a white border to show around tables when on a mobile device.
Thanks!
> History Graph Bug Fix and New Box Look

- back/pialert.py
Make pushsafer request use the existing requests module as the module it relied on is not installed. 
Remove the sending of duplicate NTFY Messages
> Fix Pushsafer Support and Duplicate NTFY Messages

- front/deviceDetails.php
Fixes #40
Fixes navigation buttons disabling after a refresh of the page. (Line 960)
Makes the selected device persistent across page refresh, instead of going back to the first selected one
> Device Navigation Fixes

- Dockerfile
- back/pialert.py
- back/report_template.txt
- config/version.conf
- front/php/server/db.php
- front/php/server/devices.php
- front/php/server/events.php
- front/php/server/util.php
Fixes #48 fully.  It was a timezone error where SQL would not fetch the correct time relative to the current system timezone. This has now been fixed and presence graphs should work properly.
Should fix #51. Please confirm. Adds extra check before sending notification.
Removes cycle from text report because it does not provide useful information since there is only one scan cycle.
> Fix timezone issues and duplicate down notifications

- back/pialert.py
- config/pialert.conf
I've made a couple of minor changes I hope you will accept with reference to #96:
- There is now a `text` option for `WEBHOOK_PAYLOAD` to just send plain text compatible with Slack and Google chat and others
- You can set a reporting level using a new config called `EVENT_LEVEL`.
0 - No reports
1 - Internet changes only
2 - New devices (plus the above)
3 - Down devices (plus above)
4 - Events (plus above) i.e. everything
The `EVENT_LEVEL` only applies to `text` payloads but if you want to use it for other types obviously you can. It's just to reduce the number of alerts.
> Webhook text

- .dockerignore
- Dockerfile
This PR reduces the uncompressed image size by about 50MB. This is because when RUN chmod is utilized all of the files where the permissions are changed become a new layer.
Instead this uses the relatively new COPY args --chmod and --chown. This may also help with other misc file permission issues as it will ensure all files are r/w by both root and www-data.
There are some other space saving possibilities, especially around the the update_vendors.sh script but I thought this would be a simple one to start with.
> Reduce docker image size by setting permissions at copy stage

- .github/workflows/docker.yml
Poking around the latest image noticed that the docs folder and other files are being included in the build COPY operation even though they are in the .dockerignore.
```bash
/home/pi/pialert
total 132K
drwxrwxrwx 1 root root 4.0K Dec 12 08:15 .
drwxr-xr-x 1 pi   pi   4.0K Dec 12 08:15 ..
-rwxrwxrwx 1 root root  268 Dec 12 08:14 .dockerignore
-rwxrwxrwx 1 root root  297 Dec 12 08:14 .env
drwxrwxrwx 1 root root 4.0K Dec 12 08:14 .github
-rwxrwxrwx 1 root root   47 Dec 12 08:14 .gitignore
-rwxrwxrwx 1 root root 1.5K Dec 12 08:14 Dockerfile
-rwxrwxrwx 1 root root  35K Dec 12 08:14 LICENSE.txt
-rwxrwxrwx 1 root root 6.4K Dec 12 08:14 README.md
drwxrwxrwx 1 root root 4.0K Dec 12 08:14 back
drwxrwxrwx 1 root root 4.0K Dec 18 18:06 config
drwxrwxrwx 1 root root 4.0K Dec 18 18:06 db
-rwxrwxrwx 1 …
```
> Use path context so dockerignore is respected

- front/devices.php
Remove obsolete column changing for mobile. 
This is now handled by the column selector in the maintenance tab.
> Fix table mobile view

- back/pialert.py
the get_plugin_config function loops thru all directories (and sub directories) of the /front/plugins directory.
It does not need to go to subdirecotries and failed when there was a __pycache__ directory.
> get_plugin_config changed to top level folders

- .github/workflows/docker_dev.yml
- .github/workflows/docker_prod.yml
the docker cache was pointed incorrectly to docker hub making the cache location a problem and making the cleaner to fail.
additional info here: https://github.com/jokob-sk/Pi.Alert/pull/254#issuecomment-1605339822
> fix: docker cache to github registry mistake

- pialert/device.py
As per the discussion [here](https://github.com/jokob-sk/Pi.Alert/discussions/303) this is a minimal change which appears to mitigate the race condition by not adding devices who's dev_Name is already `(name not found)` to the recordsNotFound array preventing them from overwriting a change the user made since the function started running.  It will still overwrite a change made to a `(unknown)` dev_Name.
> Mitigate race condition in update_device_names

- pialert/plugin.py
When using plugins that can return customised names, such as UniFi, a name can contain `'` characters, breaking the SQL query in plugin.py.
For example, on UniFi I have a device named `Steve's Phone`, which evaluates to `...Watched_Value1 = 'Steve's Phone',...` in the query, causing a `sqlite3.OperationalError: near "s": syntax error` and crashing the container in my case.
There is also the potential of a malicious actor being able to control the input, and doing something with the database (like adding a new user). But that can only happen if they can control the source of data from a plugin, and the crashing was more of an annoyance for me.
> Fix SQL injection/error

- front/deviceDetails.php
<h3>Update deviceDetails.php (front/)</h3>
- The Nmap and Tools section has been divided into "tab control".
- Nmap tab is now only shown if it is a device that contains MAC address
- Split content into Nmap and Tools tab
- Added icon in "Nmap" tab
- Added icon in "Tools" tab
> Split "Nmap" and "tools" tabs in deviceDetails.php

- front/plugins/unifi_import/config.json
- front/plugins/unifi_import/script.py
1) fix: port of UniFi controller not passed to [pyunify](https://github.com/finish06/pyunifi). now works for non-default ports of the UniFi controller.
2) new feature: allow user to define if pyunifi should verify the SSL certificate of the UniFi controller (defaults to `false`)
3) maintenace: remove option for protocol (http:// vs https://) as it is not passed to pyunify and pyunifi always uses https
> UniFi: bugfix and new feature

- front/plugins/nmap_scan/config.json
Texts are missing in the Spanish translations, the Spanish translations of the nmap_scan plugin have been fixed.
<h3>Update config.json (front/plugins/nmap_scan/)</h3>
- Updated config.json file with new fixes in Spanish translations
> Fixes in the Spanish translations of the Nmap Scan plugin

- front/maintenance.php
The URLs of the ImportCSV and ExportCSV functions are not absolute paths and this causes an error with a reverse proxy configuration.
<h3>Update maintenance.php (front)</h3>
- Fixed URL of ImportCSV function
- Fixed URL of ExportCSV function
> Url fixes for the ImportCSV and ExportCSV functions in maintenance.php

- front/plugins/csv_backup/README.md
- front/plugins/csv_backup/README_DE.md
- front/plugins/csv_backup/README_ES.md
- front/plugins/csv_backup/config.json
- Created file README_ES.md (File translated into Spanish from README.md)
- Created file README_DE.md (File translated into German from README.md)
- Added link in README.md to the Spanish and German translations
- Added Spanish translation (Plugin)
- Added German translation (Plugin)
<h3>Create README_ES.md (/front/plugins/csv_backup/)</h3>
- Created the README_ES.md file (front/plugins/csv_backup/) which is a version of README.md (front/plugins/csv_backup/) translated into Spanish.
<h3>Create README_DE.md (/front/plugins/csv_backup/)</h3>
- Created the README_DE.md file (front/plugins/csv_backup/) which is a version of README.md (front/plugins/csv_backup/) translated into Deutsch.
<h3>Update README.md …
> Pi.Alert - Fixes CSV Backup (Plugin) translations

- front/settings.php
Problem detected in the "saveSettings" function in "settings.php" with reverse proxies, it is corrected by changing relative url to absolute url so that it works correctly with reverse proxies.
<h3>Update settings.php (/front/)</h3>
- The "saveSettings" function is corrected by changing the relative url to an absolute url so that it works correctly with reverse proxies.
> Fix "saveSettings" function in settings.php for reverse proxies

- front/plugins/pihole_scan/config.json
Problem detected in the "default_value" string of the "CMD" function in "config.json" of the "pihole_scan" plugin, which causes it to cause an error in the Pi.Alert configuration file, it is corrected by adding {s-quote}.
<h3>Update config.json (/front/plugins/pihole_scan)</h3>
- "CMD" function is corrected by adding {s-quote} in "default_value"
> Pi.Alert - Fix "CMD" function in pihole_scan plugin

- front/plugins/unifi_import/config.json
- front/plugins/unifi_import/script.py
This feature gives the user the option to perform a full import of all devices known to the unifi controller
- user has the option to perform the import once or always
- on 'once' the import is done once - during this run all devices are shown online, afterwards only the actually online devices are shown online
- on 'always' the import is done during each unifi_import run - all devices are shown online continously
You might want to double check, as I had to merge some changes in the config.json file for the plugin, not sure if it worked out correctly
p.s.: sorry for the delay
> Added functionality to perform a full import

- front/php/server/devices.php
Device Types in the Device details view are not loaded. The API request results in a 500 Internal Server Error.
The issue stems from a missed removal of `getNetworkTypes()` call inside the `getDeviceTypes()` function in `php/server/devices.php` in the commit https://github.com/jokob-sk/Pi.Alert/commit/07367a2ca32f253b6d9890b2e104df6e82bef05f.
Output of `getDeviceTypes()` function call:
```console
root@nas:/home/pi/pialert/front/php/server# php -r "require 'devices.php'; getDeviceTypes();"
PHP Fatal error:  Uncaught Error: Call to undefined function getNetworkTypes() in /home/pi/pialert/front/php/server/devices.php:860
Stack trace:
#0 Command line code(1): getDeviceTypes()
#1 {main}
thrown in /home/pi/pialert/front/php/server/devices.php on line 860
```
This PR fixes that by removing the …
> Fix device types not loading in device details page

- front/deviceDetails.php
This PR shows the current device icon on the device detail page and also shows it change as you type/select a different icon.
**Is your feature request related to a problem? Please describe.**
Not being able to see the current icon (visually) associated with a device on the detail page is a little frustrating. It would also be nice to be able to try some different phrases to see if an icon exists (ex: `light` doesn't work by `lightbulb` does).
**Describe the solution you'd like**
The icon is displayed next to the text and changes in real time as you type
**Describe alternatives you've considered**
To find a new icon I would manually going to the [font awesome search form](https://fontawesome.com/search). To see the way the current icon looks I would go back to the device list and view it …
> Show current device icon as it changes

- dockerfiles/README.md
- dockerfiles/start.sh
This could be useful when using multiple subnets to hide the web interface from all untrusted networks by adding variables in the docker startup script to set the listener address for the nginx webserver.
Set "LISTEN_ADDR" in the docker environment variable. (this is an optional variable, and if not set, nginx listens to all container network interfaces.)
**Example in docker environment**:
LISTEN_ADDR=172.17.0.1
> Add option to set IP Address for web interface in Docker env

- front/plugins/db_cleanup/script.py
Fixes a bug introduced in [this refactor commit](https://github.com/jokob-sk/Pi.Alert/commit/a5b952f18c21fea7983efa56399c12f254d6800e) which caused the DB cleaning script to delete all new devices even if the configuration parameter `hourstokeepnewdevice` has a value of `0`.
The cause is that before the refactor the parameters of the function cleanup_database were integer values, however after the refactor they are string values, causing this issue and potentially other unexpected behaviors.
This may be related to #474 and #481
> Fix DB Clean plugin new devices deletion bug

- pialert/helper.py
Fixes an issue with date parsing for update check. 
If the host has a timezone explicitly set other than UTC with a TZ environment variable, the parsing of the downloaded release date does not produce the expected timestamp to properly compare against the buildtimestamp. This makes the parser timezone aware (the %z addition) and uses the builtin timestamp function to produce the expected timestamp. 
Tested on host with TZ set:
```
>>> import datetime
>>> dateTimeStr = '2023-11-11T01:48:45Z'
>>> int(datetime.datetime.strptime(dateTimeStr, '%Y-%m-%dT%H:%M:%SZ').strftime('%s'))
1699685325
>>> int(datetime.datetime.strptime(dateTimeStr, '%Y-%m-%dT%H:%M:%S%z').timestamp())
1699667325
>>> release = int(datetime.datetime.strptime(dateTimeStr, '%Y-%m-%dT%H:%M:%S%z').timestamp())
>>> release …
```
> Fix date parsing for release check

- front/plugins/_publisher_email/email_smtp.py
Sending mail with the publisher mail plugin resulted in error
`NameError: name 'smtp_timeout' is not defined`
Fix to /front/plugins/_publisher_email/email_smtp.py
- `smtp_timeout` is now an argument to the `send_mail` function
> FIX unable to send mail with publisher mail plugin

- front/js/graph_online_history.js
Depending on how many devices are contained in the list, the y-axis may contain floating point numbers. This does not make sense.
> Update jokob-sk graph_online_history.js

- front/plugins/_publisher_mqtt/mqtt.py
`\s` is invalid in Python3 and must be `\\s` now
12:37:02 [Plugin utils] ---------------------------------------------
12:37:02 [Plugin utils] display_name: MQTT publisher
12:37:02 [Plugins] Executing: python3 /app/front/plugins/_publisher_mqtt/mqtt.py devices={devices}
12:37:03 /app/front/plugins/_publisher_mqtt/mqtt.py:362: SyntaxWarning: invalid escape sequence '\s'
devDisplayName  = re.sub('[^a-zA-Z0-9-_\s]', '', device["dev_Name"]) 
Traceback (most recent call last):
File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 26, in <module>
from plugin_utils import getPluginObject
> Fixed invalid escape sequence in MQTT publisher

- front/plugins/_publisher_mqtt/mqtt.py
Ref issue https://github.com/jokob-sk/NetAlertX/issues/702
`json_dumps` adds quotations to the string:
```
>>> import json
>>> json.dumps("home")
'"home"'
>>>
```
So we either need to stick to json only or check the instance and if the instance is just a string, then do not do any `json_dumps`.
> Fix for MQTT device tracker adding quotes to payload

- front/plugins/_publisher_mqtt/config.json
- front/plugins/_publisher_mqtt/mqtt.py
Changed client creation logic to V2 API as we are already using Paho2.0. Changed version selection from Paho version (which should not have been a user choice) to MQTT Protocol selection, which can be v3 or v5. Most modern MQQTT brokers like Mosquitta or EMQX support v5. Set default MQTT version to 5.
Previously, when a user selected Paho V2, the callback signature was invalid and Python errored out.
> Resolved issue with Paho V2 API

- Dockerfile
- Dockerfile.debian
- docker-compose.yml
- front/plugins/mikrotik_scan/config.json
- front/plugins/mikrotik_scan/mikrotik.py
Trying to fix the mtscan plugin, but I had some questions about NetAlertX.
@jokob-sk check mail!
> chore: fixed mtscan and Dockerfile

- front/deviceDetails.php
- front/php/templates/footer.php
DEFER in footer for ui_components breaks device details page
Typo in CSS in device details
> Fixes to CSS and scripts not loading properly

- front/appEventsCore.php
- front/report.php
- front/userNotifications.php
When using a reverse proxy with Subpath, the notifications don't load. The call is made to http://host/api/user_notifications.json instead of http://host/netalertx/api/user_notifications.json.
When I compared it to the [table_devices.json request](https://github.com/jokob-sk/NetAlertX/blob/30750a9449963d22a66b06aa129fa5b4ac59814e/front/devices.php#L403) (which works), I realized that it probably works there because it's relative. When I changed it manually on the server to test, the notifications appeared.
I don't think changing this should cause any problems, as table_devices.json already works like this. However, as everything in IT is strange, any small change can cause unexpected errors, so I suggest you test it too. :)
Not working:
Working:
Edit:
I saw some other requests that were …
> Fixes to work using a reverse proxy

- front/plugins/_publisher_mqtt/mqtt.py
This change adds Model information for HomeAssistant that shows in Device info instead of showing Unknown. 
Users who previously had their devices discovered in HomeAssistant won't have this changed by default. Users need to delete their devices from HomeAssistant or [Force update MQTT for each device](https://github.com/jokob-sk/NetAlertX/blob/d1d6d7f1ec0372eccda7a8aba96fad3b7e1bed87/front/plugins/_publisher_mqtt/README.md). 
After change:
> Update MQTT to send model as device name

- server/database.py
- server/device.py
- server/networkscan.py
- server/plugin.py
When a scan detects a device is online but no initial connection event exists, this creates a connection event at scan time so the presence monitor can properly function.
> Add events for imported devs

- front/plugins/README.md
- front/plugins/ipneigh/README.md
- front/plugins/ipneigh/config.json
- front/plugins/ipneigh/ipneigh.py
`IPNEIGH` is a new device discovery plugin that uses the `ip neigh` command to read from both the ARP and NDP table.
The main objective of this plugin is to allow for discovery of IPv6 devices which use NDP for address resolution, and aren't detectable by `ARPSCAN`.
The plugin is extremely simple. First it runs a ping on multicast address `ff02::1` which is directed at every IPv6 device from the local network, this causes the network stack to send NDP solicitation requests and populates the NDP table. Note that every device will answer with only one of its addresses, so only those addresses will appear in the table, unless discovered by normal operation.\
Then using the `ip neigh` command it retrieves every neighbouring IP, both v4 and v6, and adds them to the database. It will not …
> Add IPNEIGH plugin for IPv4/6 discovery using the `ip neigh` command

- front/plugins/mikrotik_scan/config.json
- front/plugins/mikrotik_scan/mikrotik.py
reopen of #938 
> It was removed as part of https://github.com/jokob-sk/NetAlertX/pull/759 (exactly: https://github.com/jokob-sk/NetAlertX/pull/759/files#diff-3141c3ddff99ee9cccc877150d8bd75a6a5227c3f049d6fe7809ef27b77cbb71L91 ), however comments are used to provide custom device names for Mikrotik's static leases
I have:
- removed unused imports and unused "ips" param, 
- created the device_name variable that tries to determine the name in order: comment>hostname>"(unknown)" fallback (so nslookup and other plugins can continue resolving from here)
- used all watchedValues that are defined in config.json
> Restore manual naming of static leases using comments for MKSCAN + cleanups

- Dockerfile
- Dockerfile.debian
- docker-compose.yml
- front/plugins/README.md
- front/plugins/asuswrt_import/README.md
- front/plugins/asuswrt_import/config.json
- front/plugins/asuswrt_import/script.py
- install/install_dependencies.debian.sh
You can now import your devices from AsusWRT routers. Check Readme for more info.
Fixes https://github.com/jokob-sk/NetAlertX/issues/624
> Added AsusWRT device import plugin

- front/js/common.js
Hi @jokob-sk,
Changed the absolute path URL to relative path URL in common.js, this is a fix for issues with reverse proxy servers.
<h3>Update common.js (/front/js/common.js)</h3>
Change absolute path url /php/server/query_json.php to relative path url php/server/query_json.php in common.js to fix issues for reverse proxies
<h2>Test</h2>
Tested locally and works fine
> Changed the "absolute URL" target to "relative URL" in common.js

- front/plugins/omada_sdn_openapi/config.json
Since the plugin folder was renamed from `omada_sdn_openapi_import` to `omada_sdn_openapi` the `RUN` command should be changed as well for the plugin to work correctly.
> OMDSDNOPENAPI - Run command change due to plugin folder rename

- front/devices.php
Hi @jokob-sk,
Changed the absolute path URL to relative path URL in devices.php, this is a fix for issues with reverse proxy servers.
<h3>Update devices.php (/front/devices.php)</h3>
Changed three absolute path URLs to relative path URLs
<h2>Test</h2>
Tested locally and works fine
> Changing absolute path URL to relative path URL in devices.php

- Dockerfile
- Dockerfile.debian
- server/notification.py
As SMTP defines a limit of 1000 characters per line, sane MTA add a newline to not break the SMTP standard.
Unfortunately those stupid little MTAs don't know anything about HTML, and just add the line break whereever they see fit... even if that's in the middle of a link, which then breaks the link.
By properly indenting the HTML that's generated, we're keeping those stupid MTAs from messing without our precious HTML, ensuring that all links are still working.
See https://github.com/jokob-sk/NetAlertX/issues/1049
> properly indent HTML tables in report emails to fix broken links

- front/js/handle_version.js
- front/php/components/graph_online_history.php
- front/php/templates/header.php
- front/settings.php
recent changes to the codebase use /php for get requests. This changes those to relative paths to allow for reverse proxy usage.
> use relative paths for reverse proxy

- front/plugins/freebox/freebox.py
New entries extracted from latest Freebox Server web interface
If a new device type has not been mapped yet, do not fail the scan but return "Unknown" instead (for future types)
Fix #1084
> Update freebox.py: add missing entries in device_type_map

- .github/ISSUE_TEMPLATE/documentation-feedback.yml
Adds a new GitHub issue template for reporting documentation-related suggestions, inconsistencies, or improvements.
This template helps contributors provide clear, categorized feedback on docs, making it easier to track and prioritize structural or content-related issues separately from codebase bugs or feature requests.
Includes fields for:
- Affected document/section
- Description of the issue
- Proposed solution
- Type of documentation issue
- Optional implementation offer
Helps improve overall clarity, uniformity, and contributor experience with documentation.
closes #1093
> add documentation feedback issue template

- front/php/components/logs.php
This is a simple change to include the full path to the file.  I actually needed to debug to figure out why /app/log/nginx/error.log wasn't populating.  Not all the logs are in the same folder so it makes sense to specify location for each.
> Make it easier to find the corresponding log files

- front/php/server/db.php
Php7.2 cryptography changed to not allow empty encryption strings.  A blank string is acceptable. though.
> Change default encryption key to an empty string
